//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientGraphique.ServiceVelibReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VelibStation", Namespace="http://schemas.datacontract.org/2004/07/IWS_Velib")]
    [System.SerializableAttribute()]
    public partial class VelibStation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableBikeStandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AvailableBikesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BikeStandsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableBikeStands {
            get {
                return this.AvailableBikeStandsField;
            }
            set {
                if ((this.AvailableBikeStandsField.Equals(value) != true)) {
                    this.AvailableBikeStandsField = value;
                    this.RaisePropertyChanged("AvailableBikeStands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AvailableBikes {
            get {
                return this.AvailableBikesField;
            }
            set {
                if ((this.AvailableBikesField.Equals(value) != true)) {
                    this.AvailableBikesField = value;
                    this.RaisePropertyChanged("AvailableBikes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Banking {
            get {
                return this.BankingField;
            }
            set {
                if ((this.BankingField.Equals(value) != true)) {
                    this.BankingField = value;
                    this.RaisePropertyChanged("Banking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BikeStands {
            get {
                return this.BikeStandsField;
            }
            set {
                if ((this.BikeStandsField.Equals(value) != true)) {
                    this.BikeStandsField = value;
                    this.RaisePropertyChanged("BikeStands");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVelibReference.IWSVelib")]
    public interface IWSVelib {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSVelib/GetListStations", ReplyAction="http://tempuri.org/IWSVelib/GetListStationsResponse")]
        string[] GetListStations(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSVelib/GetListStations", ReplyAction="http://tempuri.org/IWSVelib/GetListStationsResponse")]
        System.Threading.Tasks.Task<string[]> GetListStationsAsync(string city);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSVelib/getStation", ReplyAction="http://tempuri.org/IWSVelib/getStationResponse")]
        ClientGraphique.ServiceVelibReference.VelibStation getStation(string city, string stationName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSVelib/getStation", ReplyAction="http://tempuri.org/IWSVelib/getStationResponse")]
        System.Threading.Tasks.Task<ClientGraphique.ServiceVelibReference.VelibStation> getStationAsync(string city, string stationName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSVelibChannel : ClientGraphique.ServiceVelibReference.IWSVelib, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSVelibClient : System.ServiceModel.ClientBase<ClientGraphique.ServiceVelibReference.IWSVelib>, ClientGraphique.ServiceVelibReference.IWSVelib {
        
        public WSVelibClient() {
        }
        
        public WSVelibClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSVelibClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVelibClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSVelibClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] GetListStations(string city) {
            return base.Channel.GetListStations(city);
        }
        
        public System.Threading.Tasks.Task<string[]> GetListStationsAsync(string city) {
            return base.Channel.GetListStationsAsync(city);
        }
        
        public ClientGraphique.ServiceVelibReference.VelibStation getStation(string city, string stationName) {
            return base.Channel.getStation(city, stationName);
        }
        
        public System.Threading.Tasks.Task<ClientGraphique.ServiceVelibReference.VelibStation> getStationAsync(string city, string stationName) {
            return base.Channel.getStationAsync(city, stationName);
        }
    }
}
